version: '3.3'

services:
  app:          
    build: . 
    container_name: cataloging_app
    working_dir: /var/www/cataloging
    volumes:
      - /var/www/cataloging:/var/www/cataloging
    ports:
      - "9011:9000"