version: '3.3'

services:
  app:          
    build: . 
    container_name: scanit_app
    working_dir: /var/www/scanit
    volumes:
      - /var/www/scanit:/var/www/scanit
    ports:
      - "9005:9000"